# Generated by Django 3.0.3 on 2020-03-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Createform', '0003_auto_20200319_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseform',
            old_name='capacity',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='courseform',
            old_name='building',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='departmentform',
            old_name='capacity',
            new_name='budget',
        ),
        migrations.RenameField(
            model_name='departmentform',
            old_name='room_name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='insructorform',
            old_name='building',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='insructorform',
            old_name='room_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='insructorform',
            old_name='capacity',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='courseform',
            name='room_name',
        ),
    ]
