# Generated by Django 3.0.3 on 2020-03-19 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Createform', '0004_auto_20200319_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prereq',
            old_name='building',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='prereq',
            old_name='room_name',
            new_name='prereqid',
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='capacity',
        ),
    ]
