# Generated by Django 3.0.3 on 2020-03-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100)),
                ('room_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
