# Generated by Django 3.0.3 on 2020-04-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course_running',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='building',
            new_name='Floor',
        ),
    ]
