# Generated by Django 3.0.3 on 2020-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200401_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_running',
            old_name='building',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='course_running',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course_running',
            old_name='budget',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='room_name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='room_number',
            field=models.IntegerField(default='01', editable=False),
        ),
    ]
