# Generated by Django 3.0.3 on 2020-04-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200402_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_running',
            name='salary',
            field=models.IntegerField(default='01', editable=False),
        ),
    ]
