# Generated by Django 3.0.3 on 2020-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200402_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor', models.CharField(max_length=100)),
                ('room_number', models.IntegerField(default='01', editable=False)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='course_running',
            old_name='salary',
            new_name='fees',
        ),
        migrations.RenameField(
            model_name='course_running',
            old_name='name',
            new_name='name1',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
