# Generated by Django 3.0.3 on 2020-06-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200603_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_running',
            old_name='name1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course_running',
            name='fees',
        ),
    ]
