# Generated by Django 3.0.3 on 2020-03-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city2', models.CharField(max_length=100)),
                ('course', models.TextField()),
                ('marks1', models.IntegerField()),
                ('Budget1', models.IntegerField()),
            ],
        ),
    ]
